bower.json, example.json, js/adapt-contrib-narrative.js, less/narrative.less, package.json, properties.schema, templates/narrative.hbs
Controls can now be placed in the text area
Fixes #101
=> Adds extra controls functionality

bower.json, package.json, properties.schema
=> Added _supportedLayout attribute

js/adapt-contrib-narrative.js
Stops the page jumping to narrative on page visit
=> Accessibility - Fix for focus on initial setup

example.json, less/narrative.less, templates/narrative.hbs
Made accessible and spread buttons to fill content width.
=> Ported _hasNavigationInTextArea from master to develop

less/narrative.less
=> Added no-touch class to hover states

templates/narrative.hbs
=> a to button

js/adapt-contrib-narrative.js
For ABU-820. Also see https://github.com/adaptlearning/adapt_framework/pull/750.
=> Add disable animation config check

js/adapt-contrib-narrative.js
see [ABU-1105](https://adaptlearning.atlassian.net/browse/ABU-1105)
=> fix issue with instruction text not being accessible

js/adapt-contrib-narrative.js
=> fixes ABU-1114

js/adapt-contrib-narrative.js
original issue: https://github.com/adaptlearning/adapt_framework/issues/848
the two components don't share the same visited property.
=> setting completion when changing orientation on mobile device issue#848

templates/narrative.hbs
replacing visited to _isVisited
=> change in hbs

js/adapt-contrib-narrative.js
Fixes https://github.com/adaptlearning/adapt_framework/issues/860
=> fixes for #860

js/adapt-contrib-narrative.js
https://github.com/adaptlearning/adapt_framework/issues/1176
=> issue-1176: trickle resize fix

less/narrative.less
Bug fix to resolve RTL issue whereby the arrows were not swapped.
=> RTL bug fix

README.md, bower.json, example.json, less/narrative.less, properties.schema, templates/narrative.hbs
Ensuring that graphics can have attribution as per adapt-contrib-graphic
=> Add attribution to narrative

README.md, bower.json, less/narrative.less
tested in IE11, Chrome and Firefox
=> amends to fix IE bug

templates/narrative.hbs
https://github.com/adaptlearning/adapt_framework/issues/1673
part of https://github.com/adaptlearning/adapt_framework/issues/1704
=> issue-1673: fix image aria label

templates/narrative.hbs
https://github.com/adaptlearning/adapt_framework/issues/833
=> removed ref to accessible-text-block

js/adapt-contrib-narrative.js
[issue/#2073](https://github.com/adaptlearning/adapt_framework/issues/2073)
Switched from manual lookup of hotgraphic component view to `Adapt` api.
dependent on [pr/2074](https://github.com/adaptlearning/adapt_framework/pull/2074)
=> fixes issue/#2073 : switch to Adapt.getViewClass

js/narrativeView.js
part of adaptlearning/adapt_framework#2269
=> switch over to the new ComponentView inview functionality

README.md, bower.json
There is a hard dependency on v4 now.
=> Resolves #2348, corrects issue with incorrect framework compatibility

properties.schema
fixes https://github.com/adaptlearning/adapt_framework/issues/2383
=> make schema defaults consistent

README.md, bower.json, example.json, js/adapt-contrib-narrative.js, js/modeEnum.js, js/narrativeView.js, less/narrative.less, properties.schema, templates/narrative.hbs
Narrative converted to use 2 spaces for indentation.
=> update to use 2 spaces for indentation

js/narrativeView.js
fixes https://github.com/adaptlearning/adapt_framework/issues/2422
=> Setup imageready after setupNarrative is called

js/adapt-contrib-narrative.js
Issue: https://github.com/adaptlearning/adapt_framework/issues/2718
=> Extend ItemsComponent model

bower.json, js/narrativeView.js
For issue [#2742](https://github.com/adaptlearning/adapt_framework/issues/2742)
=> Active item setting must conform to available range of number of items

README.md, bower.json, js/narrativeView.js, templates/narrative.hbs
see https://github.com/adaptlearning/adapt_framework/issues/2799 and https://github.com/adaptlearning/adapt_framework/issues/2808
=> remove references to deprecated code, upgrade to ES6

less/narrative.less
Related issue: https://github.com/adaptlearning/adapt_framework/issues/2891
=> Less tidy up

README.md, example.json, properties.schema
=> remove placeholder alt text from example

bower.json, js/narrativeView.js, templates/narrative.hbs
resolves https://github.com/adaptlearning/adapt_framework/issues/3052
=> Adapt 7933 narrative attribution gets read after all of the items

js/narrativeView.js, properties.schema
Resolves https://github.com/adaptlearning/adapt_framework/issues/3155
=> issue/3155 Fixed button aria-label normalisation

templates/narrative.hbs
https://github.com/adaptlearning/adapt_framework/issues/3150
* Compile directive
=> issue/3150 Added compile directive

README.md, bower.json, js/NarrativeView.js
=> Fix completion for text below image #220

bower.json, js/NarrativeView.js
https://github.com/adaptlearning/adapt_framework/issues/3009
=> ADAPT-9790 - import a11y and device singletons

templates/narrative.hbs
* Fixes #248 
[//]: # (List appropriate steps for testing if needed)
1. Pull down this PR and examine the structure in the output
[//]: # (Mention any other dependencies)
=> Fix: Normalizing template icons (fixes: #248)

js/NarrativeView.js, templates/narrative.jsx
See https://github.com/adaptlearning/adapt-contrib-narrative/issues/258 for further details.
=> Issue#258 - narrative focus being pulled on mobile fix

js/NarrativeView.js
fixes #262 
* Replace narrative view with hotgraphic view on parent, allowing for clearup on page destruction
=> Fix: Replace narrative view with hotgraphic view on parent

js/NarrativeView.js, templates/narrative.jsx
fixes #276
* Show standard mobile buttons on _hasNavigationInTextArea
=> Fix: Show standard mobile buttons on _hasNavigationInTextArea (fixes #276)

README.md, js/NarrativeView.js
#281
* remove redundant replaceInstruction function (fixes #281)
=> Fix: remove redundant replaceInstruction function (#281)

less/narrative.less
Fixes: #289 
* Updated RTL styling to remove unnecessary declarations
=> Update: Updated RTL styling (fixes: #289)

tests/e2e/narrative.cy.js
=> Fix: Update tests to meet new standards (Issue/306)

schema/component.schema.json
#316 
* isObjectId removed from schema to allow external assets to be added (fixes #316)
=> Fix: isObjectId removed from schema to allow external assets to be added (fixes #316)

.github/ISSUE_TEMPLATE/config.yml, .github/ISSUE_TEMPLATE/issue_template.md
Fixes #321
* Add new `issue_template.md` file with YAML frontmatter
* Add new `config.yml` file to disable blank template
=> Chore: Add support for new issue experience (fixes #321)
