- js/adapt-contrib-narrative.js
Issues occur in ie8 whereby neither components are loaded on first load from LMS
> Removed circular dependency on hotgraphic

- bower.json
- js/adapt-contrib-narrative.js
- package.json
If you resize the screen making it smaller the breakpoint for the view change from desktop to mobile happened at 758px. Whereas if you resize the screen making it bigger the breakpoint for the view change from mobile to desktop happened at 761px.
This creates an issue with a few pixels not syncing up with the normal breakpoints. Small issue but breaks layout on some devices that fall in to these breakpoints when changing orientation.
> Fixing breakpoint issue with the view

- bower.json
- js/adapt-contrib-narrative.js
- package.json
If you resize the screen making it smaller the breakpoint for the view change from desktop to mobile happened at 758px. Whereas if you resize the screen making it bigger the breakpoint for the view change from mobile to desktop happened at 761px.
This creates an issue with a few pixels not syncing up with the normal breakpoints. Small issue but breaks layout on some devices that fall in to these breakpoints when changing orientation.
> Fix for the breakpoint issue

- js/adapt-contrib-narrative.js
Addresses #118. Removed children('span') from replaceInstruction(). Was preventing mobileInstruction from displaying. partials/component.hbs has no span tags.
> Remove impediment to mobileInstruction.

- example.json
- properties.schema
Remove '_graphic.title' from example.json. 
'_graphic.title' doesn't appear to be referenced by js or hbs. Use of '_graphic.title' is inconsistent with other components where it is not used.
Also removed it from properties.schema.
> remove _graphic.title from example.json

- properties.schema
_globals._accessibility._ariaLabels.previous and _globals._accessibility._ariaLabels.next are used in the template but shared with hotgraphic and drawer.
> Narrative ariaRegion added to schema

- js/adapt-contrib-narrative.js
Fix for when the narrative switches to a hotgraphic component for mobile view. Component now gets appended to the 'component-container' div rather than outside of it.
> Fix for mobile component switch

- less/narrative.less
Added the narrative-hidden class to narrative-controls so the first and last arrows of the narrative are hidden.
> Hotfix to hide first / last arrows

- js/adapt-contrib-narrative.js
- less/narrative.less
This PR allows the learner to navigate through the narrative slides by clicking the progress dots on the bottom of the slide. This has been tested on IE8 +, FireFox, Chrome and Ipad.
> Navigate by clicking the progress indicator dots

- less/narrative.less
Change to fix a bug with strapline title padding adding to overall width of <button> tag which caused a rendering issue.
Strapline title inner has left padding already to counter any problems.
Direct results of <a> to <button> tag change.
Bug appears on small devices.
> Removed padding on strapline title

- js/adapt-contrib-narrative.js
This hide the next button as well as the prev button when there is one slide only!!
Fixes issue https://github.com/adaptlearning/adapt-contrib-narrative/issues/151
> Hide next button when there is one slide only

- js/adapt-contrib-narrative.js
- templates/narrative.hbs
removed image tabindexes and injected the image alt tag as a tabbable area before the title.
> bugfix/accessibility: img tabindex control

- js/adapt-contrib-narrative.js
This should resolve the issue described in ABU-1142. From my testing there seemed to be multiple related issues, but these should be resolved with this PR. One thing to note, when a narrative is replaced with its original hot graphic component (when resizing the browser window from mobile size back to desktop size), the component-inner div carries the aria-label and tabindex attributes because a11y_update hasn't run. This means that when the hot graphic popup is opened the inner div ends up in the tabbing order. When the popup is closed a11y_update is run and this issue appears no more. Obviously just sticking in a call to a11y_update when the narrative is replaced by the hotgraphic will fix this, but can someone advise if this is the right way to go? Thanks.
> Tabbing fixes for ABU-1142

- README.md
- bower.json
- templates/narrative.hbs
This was caused by a missing tabindex attribute.
> Corrects #1112, iOS issue with clicking narrative-slider-graphic

- js/modeEnum.js
- js/narrativeView.js
- less/narrative.less
- properties.schema
- templates/narrative.hbs
[#2193](https://github.com/adaptlearning/adapt_framework/issues/2193)
* Centralized breaking behaviour into one place
* Made sure focus behaviour only happens after initial render
* Fixed ios iframe breaking
* Shortened and fixed component description
* Removed `role="button"`
* Removed `a11y_text`
* Hidden image in place of label representation
* Used `a11y_heading_attrs`
List of outstanding PRs: https://github.com/adaptlearning/adapt_framework/issues/2206.
> accessibility: issue/#2193 General accessibility fixes

- README.md
- bower.json
- js/narrativeView.js
Description of issue:
Customer has reported that When testing two modules) on an Iphone 8. She is having issues with the narrative and hot graphic components - when trying to tap the + to expand the text it is greyed out and on some of them the + to expand disappears completely.
This only happens after the first narrative/graphic and is only happening when I do the modules on an Iphone 8, XS, 11 and 12. It's happening on all of them. I've tried on a number of Android and It's not happening. It's an iPhone specific problem.
Linked issue: https://github.com/adaptlearning/adapt_framework/issues/3013
> ADAPT-7825 - Narrative component - narrative strapline button issues on mobile

- bower.json
- js/narrativeView.js
Description of issue:
A bug that affects Android devices only. When trying to answer an open text input question, the keyboard will appear and immediately disappear straight after. This is still occurring after a rebuild of the course.
Steps to replicate:
Using an android device in landscape view e.g. Samsung Galaxy A21, Samsung Galaxy A21, Samsung Galaxy Tab 2, Google Pixel 3a, S10, Galaxy Tab S6, Galaxy Tab S5e, Galaxy Tab S4, Galaxy Tab S3
Launch course with an open text input component and a narrative component.
Access first page.
Scroll down to the open text input question and attempt to answer it.
The keyboard appears then disappears.
Expected Results:
Keyboard should remain on screen until the user dismisses it.
Actual Results:
Keyboard appears and then immediately disappears …
> Adapt 7865 narrative taking away focus from open text input

- js/narrativeView.js
For the following proposed enhancement: https://github.com/adaptlearning/adapt_framework/issues/3070
The aim is to make it clearer to users when they haven't interacted with the mobile Narrative / Hot Graphic elements in the correct order, i.e. skipping ahead one or more items before clicking on the strapline and therefore seeing all the content for that item. This could benefit users whether completion is set to `inview` or `allItems`.
Changes assume the `.instruction-error` and `@instruction-error` class and variable are defined in the Vanilla theme. I've also implemented these changes, which can be submitted in another PR if this one is approved.
> Mobile instruction highlighting for interaction error

- README.md
- less/narrative.less
Resolves https://github.com/adaptlearning/adapt_framework/issues/3160
* Adds a custom class to increase the size of the narrative items to 100% for desktop view
> Full width items custom class support

- README.md
- bower.json
- js/NarrativeView.js
- js/adapt-contrib-narrative.js
- package.json
requires https://github.com/adaptlearning/adapt-contrib-core/pull/84
part of https://github.com/adaptlearning/adapt_framework/issues/2799
* Switched to components.register from Adapt.register
* Use `a11y`, `device` and `notify` directly
> issue/2799 Removed redundant behaviour

- templates/narrative.hbs
part of https://github.com/adaptlearning/adapt-contrib-core/issues/145
* `a11y_attrs_heading` to `a11y_aria_level`
requires https://github.com/adaptlearning/adapt-contrib-core/pull/146
> issue/145 Automated aria heading levels

- js/NarrativeView.js
> resolve page scroll when user selects last item

- less/narrative.less
- templates/narrative.hbs
Fixes: #239 
* Removed `focus-rect` element as it's no longer required
> Fix: Removed focus-rect (fixes #239)

- less/narrative.less
Fixes: #245 
* Introduced an ellipsis overflow for the narrative strapline title for when the text is longer than the display area
> Fix: Strapline overflow fix (fixes #245)

- templates/narrative.jsx
issue #256 
* Supplied id to a11y.ariaLevel calculation in order to find componentItem relative to component
> Fix: Narrative item header level calculation

- js/NarrativeView.js
- package.json
fixes #263 
requires https://github.com/adaptlearning/adapt-contrib-core/pull/372
* Move breakpoint to medium from large
Fw version should be bumped on merge of core code
> Fix: Move breakpoint to medium from large

- js/NarrativeView.js
fixes #261 
Stop the button text from changing whilst the button still has focus after the click. Change the button text and state only after the focus has been moved.
* Delay button update until after focus
> Fix: Delay button update until after focus (fixes #261)

- templates/narrative.jsx
Fix #268 
* Moves the button labels to `<span>` tags
1. Enable a screenreader
2. Navigate to a Narrative component
3. Navigate to the previous and next buttons
4. Ensure that labels aren't read twice
> Fix: Previous and Next button labels are announced twice (fixes #268)

- js/NarrativeView.js
Fixes #271 
* Fix the animatedElement target in setFocus() when using `_isMobileTextBelowImage`. The element `.narrative__strapline-header-inner` doesn't exist when using `_isMobileTextBelowImage: true` which is why it was breaking
1. Enable `_isMobileTextBelowImage` in a Narrative component
2. Test on mobile
> Fix: Fix setFocus() when using _isMobileTextBelowImage (fixes #271)

- properties.schema
- schema/component.schema.json
- templates/narrativeContent.jsx
Item title `_ariaLevel` override removed.
Since `_ariaLevels` were [automated in Core](https://github.com/adaptlearning/adapt-contrib-core/pull/146), there's no need to manually override these now.
Fixes https://github.com/adaptlearning/adapt-contrib-narrative/issues/283
> Update: Remove _ariaLevel override property (fixes #283)

- README.md
- example.json
- properties.schema
- schema/component.schema.json
- templates/narrativeStrapline.jsx
This PR sets the item `title` as the default `strapline` text. `strapline` is no longer required and should only be set if an alternative or succinct title is required e.g. if `title` text is too long.
This prevents the need to update multiple properties that are usually the same as well as human error if this gets missed.
Fixes https://github.com/adaptlearning/adapt-contrib-narrative/issues/251
> Update: Set item title as strapline default (fixes #251)

- less/narrative.less
When `_hasNavigationInTextArea` display is enabled, the `.narrative__indicators` should span the width of their container, not inherit `width` from the default Narrative display (60% image / 40% text).
Current display:
PR displays as:
Fixes https://github.com/adaptlearning/adapt-contrib-narrative/issues/291
> Fix: override default indicators width for _hasNavigationInTextArea display (fixes #291)

- properties.schema
- schema/course.schema.json
Including the item count e.g. _"Item 1 of 3"_, in the `.narrative__controls` `aria-label` was dependant on the item having a `title`. Item count now reads regardless. 
When `_items[].title` is set,`.narrative__controls` `aria-label` reads as _"Back to **item title** (item 1 of 3)"_.
When `_items[].title` is not set,`.narrative__controls` `aria-label` reads as _"Back (item 1 of 3)"_.
Fixes https://github.com/adaptlearning/adapt-contrib-narrative/issues/293
> Update: move previous/next item count ARIA outside of title condition (fixes #293)

- properties.schema
Fixes https://github.com/adaptlearning/adapt-contrib-narrative/issues/297
* Set `title` as `required`. Without a title, the popup `dialog` won't be properly identified by assistive technologies.
> Fix: Title is required to set notify popup dialog label (fixes #297)

- bower.json
- js/NarrativeModel.js
- package.json
fixes #295
* Fix: Keep active item position on save/restore
Requires https://github.com/adaptlearning/adapt-contrib-core/pull/494
> Fix: Keep active item position on save/restore (fixes #295)

- less/narrative.less
- templates/narrativeControls.jsx
- templates/narrativeIndicators.jsx
Fixes https://github.com/adaptlearning/adapt-contrib-narrative/issues/288
* Set progress indicator variables for consistent sizing.
* Progress indicator `border` and `.is-selected` styles added.
* Progress indicator `.is-visited` icon style added. Tick icon displayed for consistency with other visited component item states.
The overall `.narrative__progress` size has increased from 12px to 16px. The screen shots shared in the [issue](https://github.com/adaptlearning/adapt-contrib-narrative/issues/288#issuecomment-1866373034) have larger icons (`@icon-size` `1.5rem` for consistency with other component item visited ticks) however this limits the amount of items we can comfortably fit visually and the preference was to keep these small.
* Display progress indicators below the image always. …
> New: completion icon added to progress indicators (fixes #288) 

- js/NarrativeView.js
#286 
* Fix: remove check for canCycleThroughPagination (fixes #286)
> Fix: remove check for canCycleThroughPagination (fixes #286)

- .github/pull_request_template.md
- js/NarrativeView.js
- properties.schema
- schema/course.schema.json
- templates/narrativeStrapline.jsx
Fix #308 
* Make `_items` titles optional
* Adds new generic fallback title `_globals._components._narrative.titleDialog` for strapline dialogs. This will only be used by screenreaders and will not be visually displayed. Defaults to `Item {{itemNumber}} of {{totalItems}}`.
* Adds new generic fallback title `_globals._components._narrative.titleStrapline`  for strapline buttons. Defaults to "Find out more"
Rework strapline dialog titles to use one of the following properties (sorted by precedence):
1.  `_items` `title`
2. `_items` `strapline`
3. `_globals._components._narrative.titleDialog`
Rework strapline button titles to use one of the following properties (sorted by precedence):
1. `_items` `strapline`
2. `_items` `title`
3. `_globals._components._narrative.titleStrapline`
> Update: Make item titles optional, create fallback title for dialogs and strapline buttons (fixes #308)

- js/NarrativeView.js
- properties.schema
- schema/course.schema.json
Fix #310
* Changes Back button's `aria-label` to "Back" (`_globals._accessibility._ariaLabels.previous`) when on the first slide
* Changes Next button's `aria-label` to "Next" (`_globals._accessibility._ariaLabels.next`) when on the last slide
* Various code optimizations (e.g. renaming variables)
These label values will need to be updated manually in existing courses.
> Fix: Change back and next button labels when at start / end (fixes #310)

- bower.json
- js/NarrativeView.js
- package.json
Fix #314 
* Use `transitionsEnded` function instead of the `transitionend` event when setting focus
* Bump required Adapt FW version to `5.39.6` due to use of `transitionsEnded`
1. Ensure that repeatedly clicking Previous or Next does not shift the page contents due to the browser trying to find the offscreen element to focus on.
2. Ensure keyboard navigation + focus is still functional
> Fix: Use transitionsEnded function instead of transitionend event when setting focus (fixes #314)

- migrations/v2.js
- migrations/v4.js
- migrations/v6.js
- migrations/v7.js
Part of https://github.com/adaptlearning/adapt_framework/issues/3631
#318 
* Migration scripts added to repo (fixes #318)
> New: Migration scripts added to repo (fixes #318)

- less/narrative.less
Fixes #325
* Ensure slide indicator icons are always centered both horizontally and vertically
**Correct**
**Incorrect**
> Fix: Ensure slide indicator icons are always centered (fix #325)

- js/NarrativeView.js
Fixes #304 
* Sets an inview toggle before registering an item as visited
> Fix: Narrative component registering as complete or partially complete before visiting (fixes #304)
